export const mockUnits = [
  {
    id: 1,
    unitName: 'Vinicius Colli',
    state: 'Minas Gerais',
    mrr: 'X',
    projectsActive: '200',
    investor: '120',
    tier: 'Walk',
    status: 'Ativo',
  },
  {
    id: 2,
    unitName: 'Robiacci',
    state: 'Minas Gerais',
    mrr: 'X',
    projectsActive: '200',
    investor: '120',
    tier: 'Walk',
    status: 'Ativo',
  },
  {
    id: 3,
    unitName: 'LUMA DEVELOPMENT - O inímigo agora é outro',
    state: 'Minas Gerais',
    mrr: 'X',
    projectsActive: '200',
    investor: '120',
    tier: 'Walk',
    status: 'Ativo',
  },
  {
    id: 4,
    unitName: 'Saman',
    state: 'Minas Gerais',
    mrr: 'X',
    projectsActive: '200',
    investor: '120',
    tier: 'Walk',
    status: 'Inativo',
  },
];
